config/routes.rb
Cassette::Application.routes.draw do
  resources :instruments do
    resources :measurements, shallow: true
  end
end

app/models/instrument.rb
class Instrument < ActiveRecord::Base
  attr_accessible :name, :description
  validates :name, presence: true, uniqueness: true
  has_many :measurements

  include PgSearch
  pg_search_scope :search, against: [:name, :description],
    using: {tsearch: {prefix: true, dictionary: "english"}},
    ignoring: :accents

  def self.text_search query
    if query.present?
      search query
    else
      scoped
    end
  end

  def to_s
    name
  end
end

app/models/measurement.rb
class Measurement < ActiveRecord::Base
  belongs_to :instrument
  attr_accessible :unit, :value, :timestamp

  scope :timelined, -> { order 'timestamp DESC' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/instruments_controller.rb
class InstrumentsController < ApplicationController
  respond_to :html
  respond_to :json, :xml, except: [:new, :edit]
  respond_to :csv, :xls, :js, only: :index

  helper_method :sort_column, :sort_direction

  def index
    @instruments = Instrument.text_search(params[:search])
                             .page(params[:page]).per(per_page)
                             .order(sort_column + ' ' + sort_direction)
    respond_with @instruments
  end

  def show
    @instrument = Instrument.find(params[:id])
    respond_with @instrument
  end
   
  def new
    @instrument = Instrument.new
    respond_with @instrument
  end

  def edit
    @instrument = Instrument.find(params[:id])
    respond_with @instrument
  end

  def create
    @instrument = Instrument.new(params[:instrument])
    flash[:notice] = "#{Instrument.model_name.human} #{t 'flash.notice.create'}" if @instrument.save
    respond_with @instrument
  end

  def update
    @instrument = Instrument.find(params[:id])
    flash[:notice] = "#{Instrument.model_name.human} #{t 'flash.notice.update'}" if @instrument.update_attributes(params[:instrument])
    respond_with @instrument
  end

  def destroy
    @instrument = Instrument.find(params[:id])
    @instrument.destroy
    flash[:notice] = "#{Instrument.model_name.human} #{t 'flash.notice.destroy'}"
    respond_with @instrument
  end

  private
  def sort_column
    Instrument.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end
    
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

  def per_page
    %w{csv xls}.include?(params[:format]) ? nil : 10
  end
end

app/controllers/measurements_controller.rb
class MeasurementsController < ApplicationController
  before_filter :load_instrument, except: [:destroy]

  respond_to :html, :json, :xml, :js

  def index
    @measurements = @instrument.measurements.timelined.page(params[:page]).per(20)
    respond_with @measurements
  end

  def new
    @measurement = @instrument.measurements.new
    respond_with @measurement
  end

  def create
    @measurement = @instrument.measurements.build(params[:measurement])
    flash[:notice] = "#{Measurement.model_name.human} #{t 'flash.notice.create'}" if @measurement.save
    respond_with @measurement, location: instrument_measurements_url(@instrument)
  end

  def destroy
    @measurement = Measurement.find(params[:id])
    instrument_id = @measurement.instrument_id
    @measurement.destroy
    flash[:notice] = "#{Measurement.model_name.human} #{t 'flash.notice.destroy'}"
    respond_with @measurement, location: instrument_measurements_url(instrument_id)
  end

  private
  def load_instrument
    @instrument = Instrument.find(params[:instrument_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def icon_tag icon, text
    icon ? raw("<i class='#{icon}'></i> #{text if text}") : text
  end

  def sortable column, title=nil, options={}
    column = column.to_s
    if column == sort_column && sort_direction == 'asc'
      direction = 'desc'
      icon = 'icon-arrow-down'
    elsif column == sort_column && sort_direction == 'desc'
      direction = 'asc'
      icon = 'icon-arrow-up'
    end
    link_to icon_tag(icon, title || column.titleize), params.merge(sort: column, direction: direction, page: nil), options
  end
end

app/helpers/instruments_helper.rb
module InstrumentsHelper
end

app/views/instruments/_download_links.html.slim
/ TODO: Extract to Helper method. Generalize behaviour.
#download_links
  small
    | Download: 
    = link_to 'CSV', instruments_path(params.merge(format: :csv))
    ||
    = link_to 'XLS', instruments_path(params.merge(format: :xls))

app/views/instruments/_form.html.slim
= simple_form_for @instrument, html: {class: 'form-horizontal'} do |f|
  fieldset
    legend= t("actions.#{controller.action_name.downcase}") + ' ' + Instrument.model_name.human
    = f.input :name, input_html: { class: 'span5' }
    = f.input :description, input_html: { class: 'span5' }

    .form-actions
      =' f.button :submit, class: 'btn-primary'
      =' link_to t('actions.cancel'), instruments_path, class: 'btn'

app/views/instruments/_instruments.html.slim
#instruments
  -if @instruments.any?
    table.table.table-striped
      thead
        tr
          th= sortable :name, Instrument.human_attribute_name(:name), remote: true
          th= sortable :description, Instrument.human_attribute_name(:description), remote: true
          th= t 'actions.actions'
      tbody
        - @instruments.each do |instrument|
          tr
            td= link_to instrument.name, instrument, rel: 'tooltip', title: t('actions.show')
            td= instrument.description
            td
              =' link_to t('actions.edit'), edit_instrument_path(instrument), class: 'btn btn-mini'
              =' link_to t('actions.destroy'), instrument, confirm: t('actions.confirm'), method: :delete, class: 'btn btn-mini btn-danger'

    = paginate @instruments, remote: true
  - else
    p
      | No results found.

app/views/instruments/_sort_params.html.slim
#sort_params
  = hidden_field_tag :direction, params[:direction]
  = hidden_field_tag :sort, params[:sort]

app/views/instruments/edit.html.haml
= render 'form'

app/views/instruments/edit.html.slim
= render 'form'

app/views/instruments/index.html.haml
%h1= t '.title'

#instruments
  = render 'instruments'

= link_to "#{t('actions.new')} #{Instrument.model_name.human}", new_instrument_path, class: 'btn btn-primary'

app/views/instruments/index.html.slim
h1= t '.title'

= form_tag instruments_path, method: 'get', id: 'instruments_search', remote: true, class: 'form-search' do
  .input-append
    = text_field_tag :search, params[:search], class: 'span4 search-query'
    = button_tag icon_tag('icon-search', t('general.search')), name: nil, class: 'btn'
  
  = render 'sort_params'
  = render 'download_links'
  = render 'instruments'

= link_to "#{t('actions.new')} #{Instrument.model_name.human}", new_instrument_path, class: 'btn btn-primary'

app/views/instruments/index.js.slim
|
  $('#sort_params').replaceWith("#{j render('sort_params')}");
  $('#download_links').replaceWith("#{j render('download_links')}");
  $('#instruments').replaceWith("#{j render('instruments')}");

app/views/instruments/index.xls.slim
table
  tr
    th ID
    th Name
    th Description
    th URL
  - @instruments.each do |instrument|
    tr
      td= instrument.id
      td= instrument.name
      td= instrument.description
      td= instrument_url(instrument)

app/views/instruments/new.html.haml
= render 'form'

app/views/instruments/new.html.slim
= render 'form'

app/views/instruments/show.html.slim
=content_for :sidebar do
  .measurements
    / TODO: Pluralize can yield bad results. Find better way.
    h4= Measurement.model_name.human.pluralize
    = link_to 'all', instrument_measurements_path(@instrument)

p
  h2= @instrument.name

dl
  dt= Instrument.human_attribute_name :description
  dd= @instrument.description

.form-actions
  =' link_to t('actions.back'), instruments_path, class: 'btn'
  =' link_to t('actions.edit'), edit_instrument_path(@instrument), class: 'btn'
  =' link_to t('actions.destroy'), @instrument, confirm: t('actions.confirm'), method: :delete, class: 'btn btn-danger'

app/views/layouts/application.html.slim
doctype html
html
  head
    title= t '.name'
    /[if lt IE 9] script src="html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag     'application', media: 'all'
    = javascript_include_tag  'application'
    = csrf_meta_tags
  meta name='viewport' content='width=device-width, initial-scale=1.0' 

  .navbar.navbar-inverse.navbar-fixed-top
    .navbar-inner
      .container
        a.btn.btn-navbar data-target='.nav-collapse' data-toggle='collapse' 
          span.icon-bar
          span.icon-bar
          span.icon-bar
        a.brand href='#'= t '.name' 
        .nav-collapse
          ul.nav
            li= link_to Instrument.model_name.human.pluralize, instruments_path

  .container
    - flash.each do |name, msg|
      .alert.fade.in class="alert-#{name == :notice ? 'success' : 'error'}"
        a.close data-dismiss='alert' 
        = msg
    .row
      .span9
        = yield
      .span3
        = yield :sidebar

app/views/measurements/_measurement.html.slim
tr
  td= measurement.timestamp
  td= measurement.value
  td= measurement.unit
  td= link_to t('actions.destroy'), measurement, confirm: t('actions.confirm'), method: :delete, class: 'btn btn-mini btn-danger'

app/views/measurements/index.html.slim
h1= t('.title') + ' ' + @instrument.to_s

= tabs do |tabs|
  - tabs.pane t('general.table') do
    table.table.table-striped
      thead
        tr
          th= Measurement.human_attribute_name :timestamp
          th= Measurement.human_attribute_name :value
          th= Measurement.human_attribute_name :unit
          th= t 'actions.actions'
      tbody#measurements
        = render @measurements
    = paginate @measurements

  - tabs.pane t('general.chart') do
    = content_tag :div, '', id: 'measurements_chart', data: { measurements: @measurements }

= link_to "#{t('actions.new')} #{Measurement.model_name.human}", new_instrument_measurement_path(@instrument), class: 'btn btn-primary'

app/views/measurements/index.js.slim
| $('#measurements').append("#{j render(@measurements)}");
- if @measurements.current_page < @measurements.num_pages
  | $('.pagination').replaceWith("#{j paginate(@measurements)}");
- else
  | $('.pagination').remove();

app/views/measurements/new.html.haml
= simple_form_for [@instrument, @measurement], html: {class: 'form-horizontal'} do |f|
  %fieldset
    %legend= "#{t("actions.#{controller.action_name.downcase}")} #{Measurement.model_name.human} #{t("general.for")} #{@instrument}"
    = f.input :timestamp, as: :string, input_html: { class: 'span5' }
    = f.input :value, input_html: { class: 'span5' }
    = f.input :unit, input_html: { class: 'span2' }

    .form-actions
      = f.button :submit, class: 'btn-primary'
      = link_to t('actions.cancel'), instrument_measurements_path(@instrument), class: 'btn'

app/views/measurements/new.html.slim
= simple_form_for [@instrument, @measurement], html: {class: 'form-horizontal'} do |f|
  fieldset
    legend= t("actions.#{controller.action_name.downcase}") + ' ' + Measurement.model_name.human + ' ' + t("general.for") + ' ' + @instrument.to_s
    = f.input :timestamp, as: :string, input_html: { class: 'span5' }
    = f.input :value, input_html: { class: 'span5' }
    = f.input :unit, input_html: { class: 'span2' }

    .form-actions
      =' f.button :submit, class: 'btn-primary'
      = link_to t('actions.cancel'), instrument_measurements_path(@instrument), class: 'btn'